version: '3'
services:
  streamlit:
    image: streamlit_app:v1
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    ports:
      - "8080:8080"
  fastapi:
    image: fast_api:v1
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_LOG_ACCESS_KEY=${AWS_LOG_ACCESS_KEY}
      - AWS_LOG_SECRET_KEY=${AWS_LOG_SECRET_KEY}
      
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - ./application/key.json:/fastapi/key.json
    ports:
      - "8000:8000"
